
# 2020-6-29

language: python

# Command to run tests
script:
    - python ./bag-cross-validate/bag_cross_validate_test.py

python:
    - "3.6"
    - "3.7"

install:
    - pip install scikit-learn
    - pip install numpy

